name: Create new release

on:
  release:
    types: [published]

jobs:
  build:
    name: Build with goreleaser
    runs-on: ubuntu-20.04

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
        id: go
      
      - name: Install dependencies
        run: |
          go get .

      - name: Run goreleaser
        uses: goreleaser/goreleaser-action@master
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}
